-- MySQL Script generated by MySQL Workbench
-- Thu Dec  9 19:50:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pd_chat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pd_chat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pd_chat` DEFAULT CHARACTER SET utf8 ;
USE `pd_chat` ;

-- -----------------------------------------------------
-- Table `pd_chat`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pd_chat`.`User` ;

CREATE TABLE IF NOT EXISTS `pd_chat`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pd_chat`.`Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pd_chat`.`Group` ;

CREATE TABLE IF NOT EXISTS `pd_chat`.`Group` (
  `group_id` INT NOT NULL AUTO_INCREMENT,
  `create_date` DATE NOT NULL,
  `group_name` VARCHAR(45) NOT NULL,
  `admin` INT NOT NULL,
  PRIMARY KEY (`group_id`, `admin`),
  UNIQUE INDEX `group_id_UNIQUE` (`group_id` ASC) VISIBLE,
  INDEX `fk_Group_User_idx` (`admin` ASC) VISIBLE,
  CONSTRAINT `fk_Group_User`
    FOREIGN KEY (`admin`)
    REFERENCES `pd_chat`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pd_chat`.`Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pd_chat`.`Message` ;

CREATE TABLE IF NOT EXISTS `pd_chat`.`Message` (
  `message_id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(1024) NOT NULL,
  `timestamp` DATE NOT NULL,
  `file` INT NOT NULL,
  `group_id` INT NOT NULL,
  `group_admin` INT NOT NULL,
  `User_user_id` INT NOT NULL,
  PRIMARY KEY (`message_id`, `User_user_id`, `group_id`, `group_admin`),
  UNIQUE INDEX `message_id_UNIQUE` (`message_id` ASC) VISIBLE,
  INDEX `fk_Message_Group1_idx` (`group_id` ASC, `group_admin` ASC) VISIBLE,
  INDEX `fk_Message_User1_idx` (`User_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Message_Group1`
    FOREIGN KEY (`group_id` , `group_admin`)
    REFERENCES `pd_chat`.`Group` (`group_id` , `admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `pd_chat`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pd_chat`.`UserInGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pd_chat`.`UserInGroup` ;

CREATE TABLE IF NOT EXISTS `pd_chat`.`UserInGroup` (
  `group_group_id` INT NOT NULL,
  `group_admin` INT NOT NULL,
  `group_user_id` INT NOT NULL,
  PRIMARY KEY (`group_group_id`, `group_admin`, `group_user_id`),
  INDEX `fk_Group_has_User_User1_idx` (`group_user_id` ASC) VISIBLE,
  INDEX `fk_Group_has_User_Group1_idx` (`group_group_id` ASC, `group_admin` ASC) VISIBLE,
  CONSTRAINT `fk_Group_has_User_Group1`
    FOREIGN KEY (`group_group_id` , `group_admin`)
    REFERENCES `pd_chat`.`Group` (`group_id` , `admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Group_has_User_User1`
    FOREIGN KEY (`group_user_id`)
    REFERENCES `pd_chat`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pd_chat`.`UserContact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pd_chat`.`UserContact` ;

CREATE TABLE IF NOT EXISTS `pd_chat`.`UserContact` (
  `user_id` INT NOT NULL,
  `contact_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `contact_id`),
  INDEX `fk_User_has_User_User2_idx` (`contact_id` ASC) VISIBLE,
  INDEX `fk_User_has_User_User1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_User_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `pd_chat`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_User_User2`
    FOREIGN KEY (`contact_id`)
    REFERENCES `pd_chat`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pd_chat`.`MessageRecipient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pd_chat`.`MessageRecipient` ;

CREATE TABLE IF NOT EXISTS `pd_chat`.`MessageRecipient` (
  `recipient_id` INT NOT NULL,
  `message_id` INT NOT NULL,
  `sender_id` INT NOT NULL,
  PRIMARY KEY (`recipient_id`, `message_id`, `sender_id`),
  INDEX `fk_User_has_Message_Message1_idx` (`message_id` ASC, `sender_id` ASC) VISIBLE,
  INDEX `fk_User_has_Message_User1_idx` (`recipient_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Message_User1`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `pd_chat`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Message_Message1`
    FOREIGN KEY (`message_id` , `sender_id`)
    REFERENCES `pd_chat`.`Message` (`message_id` , `User_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
